pipeline:
  identifier: Build_lithesheeli1_GitHubActions1_1718949879404
  name: Build GitHubActions1
  orgIdentifier: default
  projectIdentifier: second_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: lithesheeli1/GitHubActions1
  stages:
    - steps:
        - name: my-step
          run: echo "Hello"
